<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	  <UserSecretsId>6ed02a90-a026-4e8a-ad1c-122c2a1369fd</UserSecretsId>
  </PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Cuidemoslos.Domain\Cuidemoslos.Domain.csproj" />
		<ProjectReference Include="..\Cuidemoslos.BLL\Cuidemoslos.BLL.csproj" />
		<ProjectReference Include="..\Cuidemoslos.DAL\Cuidemoslos.DAL.csproj" />
		<ProjectReference Include="..\Cuidemoslos.Services\Cuidemoslos.Services.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Middleware\" />
	  <Folder Include="wwwroot\img\" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="AspNetCore.HealthChecks.System" Version="9.0.0" />
	  <PackageReference Include="FluentValidation" Version="11.9.0" />
	  <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="2.3.0" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	    <PrivateAssets>all</PrivateAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	  <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
	  <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
	  <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.4" />
	</ItemGroup>
</Project>
